//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NFineBaseEntities : DbContext
    {
        public NFineBaseEntities()
            : base("name=NFineBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Sys_User> Sys_User { get; set; }
        public virtual DbSet<Sys_UserLogOn> Sys_UserLogOn { get; set; }
        public virtual DbSet<Sys_Log> Sys_Log { get; set; }
        public virtual DbSet<Z_Room> Z_Room { get; set; }
        public virtual DbSet<Z_EquipmentLog> Z_EquipmentLog { get; set; }
        public virtual DbSet<Z_Equipment> Z_Equipment { get; set; }
        public virtual DbSet<Z_Course> Z_Course { get; set; }
        public virtual DbSet<Z_SchoolTime> Z_SchoolTime { get; set; }
        public virtual DbSet<Z_SectionTime> Z_SectionTime { get; set; }
        public virtual DbSet<Z_Attendance> Z_Attendance { get; set; }
        public virtual DbSet<Z_AttendanceDetails> Z_AttendanceDetails { get; set; }
        public virtual DbSet<Z_Class> Z_Class { get; set; }
        public virtual DbSet<Z_Grade> Z_Grade { get; set; }
        public virtual DbSet<Z_Profession> Z_Profession { get; set; }
        public virtual DbSet<Z_Student> Z_Student { get; set; }
        public virtual DbSet<Z_Department> Z_Department { get; set; }
    }
}
