//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_AttendanceDetails
    {
        public string F_ID { get; set; }
        public string Z_A_F_ID { get; set; }
        public string F_StuName { get; set; }
        public string F_StuNo { get; set; }
        public Nullable<System.DateTime> F_AttenTime { get; set; }
        public string F_ClassNo { get; set; }
        public Nullable<bool> F_Flag { get; set; }
        public string F_Result { get; set; }
    
        public virtual Z_Attendance Z_Attendance { get; set; }
    }
}
