//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_Attendance
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Z_Attendance()
        {
            this.Z_AttendanceDetails = new HashSet<Z_AttendanceDetails>();
        }
    
        public string F_ID { get; set; }
        public string F_ClassRoomNo { get; set; }
        public Nullable<System.DateTime> F_InitiatedTime { get; set; }
        public string F_TNum { get; set; }
        public string F_CourseNo { get; set; }
        public Nullable<bool> F_Flag { get; set; }
        public string F_ClassNo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Z_AttendanceDetails> Z_AttendanceDetails { get; set; }
    }
}
