//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_Class
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Z_Class()
        {
            this.Z_Student = new HashSet<Z_Student>();
        }
    
        public string F_Id { get; set; }
        public string Z_P_F_ID { get; set; }
        public string Z_G_F_ID { get; set; }
        public string F_ClassName { get; set; }
        public string F_ClassNo { get; set; }
    
        public virtual Z_Grade Z_Grade { get; set; }
        public virtual Z_Profession Z_Profession { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Z_Student> Z_Student { get; set; }
    }
}
