//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_Course
    {
        public string F_Id { get; set; }
        public string F_RoomName { get; set; }
        public string F_RoomCode { get; set; }
        public string F_CourseTimeType { get; set; }
        public string F_FullName { get; set; }
        public string F_EnCode { get; set; }
        public string F_TeacherNo { get; set; }
        public string F_TeacherName { get; set; }
        public string F_Major { get; set; }
        public string F_Grade { get; set; }
        public string F_Class { get; set; }
        public Nullable<int> F_StudentCount { get; set; }
        public string F_SchoolYear { get; set; }
        public string F_Term { get; set; }
        public string F_BeginWeek { get; set; }
        public string F_EndWeek { get; set; }
        public string F_WeekCount { get; set; }
        public string F_Week { get; set; }
        public Nullable<int> F_SortCode { get; set; }
        public Nullable<bool> F_DeleteMark { get; set; }
        public Nullable<bool> F_EnabledMark { get; set; }
        public string F_Description { get; set; }
        public Nullable<System.DateTime> F_CreatorTime { get; set; }
        public string F_CreatorUserId { get; set; }
        public Nullable<System.DateTime> F_LastModifyTime { get; set; }
        public string F_LastModifyUserId { get; set; }
        public Nullable<System.DateTime> F_DeleteTime { get; set; }
        public string F_DeleteUserId { get; set; }
    }
}
