//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_EquipmentLog
    {
        public string F_Id { get; set; }
        public string F_RoomNo { get; set; }
        public string F_RoomName { get; set; }
        public string F_EquipmentNo { get; set; }
        public string F_EquipmentName { get; set; }
        public string F_LogType { get; set; }
        public Nullable<System.DateTime> F_Date { get; set; }
        public string F_Account { get; set; }
        public string F_NickName { get; set; }
        public string F_FullName { get; set; }
        public string F_Description { get; set; }
        public Nullable<System.DateTime> F_CreatorTime { get; set; }
        public string F_CreatorUserId { get; set; }
    }
}
