//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Z_SchoolTime
    {
        public string F_Id { get; set; }
        public string F_SchoolYear { get; set; }
        public string F_Term { get; set; }
        public System.DateTime F_SchoolTime { get; set; }
    }
}
